server:
  servlet:
    context-path: /cont-gas
  port: ${SERVE_PORT:5000}
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/cgastos}
    username: ${MYSQL_USERNAME:admin}
    password: ${MYSQL_PASSWORD:qwe123}
  jpa:
    properties:
      hibernate:
        show_sql: true
        #format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
via-cep:
  url: "https://viacep.com.br/ws"